### ISSUE TITLE
Make favico

### ISSUE THREAD

**Issue by mwang87** [mwang87/ReDU-MS2-GNPS#103]

**Comment by alan-jarmusch** [comment]
@mwang87 16x16 and 32x32 version

![favicon-16x16](https://user-images.githubusercontent.com/41308046/66611539-c0cdf400-eb73-11e9-8436-30aaeeccc531.png)
![favicon-32x32](https://user-images.githubusercontent.com/41308046/66611540-c0cdf400-eb73-11e9-873f-990115578ac3.png)
