### ISSUE TITLE
[NCBI taxon] Add two skin microbial strains C. acnes and S. aureus

### ISSUE THREAD

**Issue by amcaraballor** [mwang87/ReDU-MS2-GNPS#127]
The following strains need to be included into the current ReDu template:
267747|Cutibacterium acnes KPA171202 
Staphylococcus aureus JE3 (this one does not have Taxonomy ID in NCBI). 
Note: Both strains used in this study: https://www.biorxiv.org/content/10.1101/594010v1.full

**Comment by alan-jarmusch** [comment]
Thank you for the suggested additions and your interest in ReDU! The following terms have been added to the ReDU template.

**NCBITaxonomy**

 * 267747|Cutibacterium acnes KPA171202
 * not specified|Staphylococcus aureus JE3

**The following steps need to be done for these terms to appear.**
1. Please make a new copy of the ReDU template from Google Sheets
2. Copy and paste special **"paste values only"** any information that you had previously completed in an old template into the updated template.
3. The new terms should appear as valid

**Note**
The drag-and-drop validator is updated periodically. The new values might not be recognized in the latest version if you quickly complete the template. If the only errors are related to the new terms, then you can continue to upload to MassIVE. Please double-check correct inclusion of your data submission.

Thank you again for your interest in ReDU,
the ReDU admins
