### ISSUE TITLE
Add Cucumis melo and B. subtilis

### ISSUE THREAD

**Issue by mvictoriaberlanga** [mwang87/ReDU-MS2-GNPS#128]
Cucumis melo (NCBI:txid3656) and Bacillus subtilis subsp. subtilis NCIB 3610 (NCBI:txid535026) need to be included into the current ReDu template.
Thank you.

**Comment by alan-jarmusch** [comment]
Thank you for the suggested additions and your interest in ReDU! The following terms have been added to the ReDU template.

**NCBITaxonomy**
 * 3656|Cucumis melo
 * 535026|Bacillus subtilis subsp. subtilis NCIB 3610 = ATCC 6051

**The following steps need to be done for these terms to appear.**
1. Please make a new copy of the ReDU template from Google Sheets
2. Copy and paste special **paste values only** any information that you had previously completed in an old template into the updated template.
3. The new terms should appear as valid

**Note**
The drag-and-drop validator is updated periodically. The new values might not be recognized in the latest version if you quickly complete the template. If the only errors are related to the new terms, then you can continue to upload to MassIVE. Please double-check correct inclusion of your data submission.

Thank you again for your interest in ReDU,
the ReDU admins
