### ISSUE TITLE
[Add taxononmy ID] Amycolatopsis sp. AA4

### ISSUE THREAD

**Issue by amcaraballor** [mwang87/ReDU-MS2-GNPS#185]
Please, add 1896961|Amycolatopsis sp. AA4 
[https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1896961]
Thanks,
MC.

**Comment by alan-jarmusch** [comment]
@amcaraballor 

**Thank you for the suggested additions and your interest in ReDU!** <br> In an attempt to restrict uncontrolled inflation of terms, we have added options or have suggested the use of existing terms that we believe capture your information sufficiently. We realize this restriction may result in the loss of specificity. Therefore, the standard ReDU sample information should be used for broad assessments and data exploration, and suggest that more detailed analysis should be performed using additional metadata from each study (accessed via individual MassIVE ID). If additional terms are necessary or if you believe the added options are insufficient, we welcome discussion via a reply to this message.<br> Thank you again for your interest in ReDU, -the ReDU admins <br>

**Re: "Please, add 1896961|Amycolatopsis sp. AA4"**
* the term "1896961|Amycolatopsis sp. AA4" has been added to the template
