### ISSUE TITLE
Updated metadata options

### ISSUE THREAD

**Issue by eelijah254** [mwang87/ReDU-MS2-GNPS#196]
Hi all, 

A few requests: 

1) for sample exctractions can 80% methanol be added
2) for UBERONBodyPart can cerebrospinal fluid be added
3) for DOIDCommonName, can HIV, Alzheimer's disease, and HIV-associated Neurocognitive disorder be added?

Thank you!

-Emmanuel

**Comment by alan-jarmusch** [comment]
@eelijah254 the following terms have been added

**Comment by alan-jarmusch** [comment]
methanol-water (4:1)

cerebrospinal fluid	(UBERON:0001359)

human immunodeficiency virus infectious disease	(DOID:526)
Alzheimer's disease	(DOID:10652)
HIV-associated neurocognitive disorder	(no DOID available)
