### ISSUE TITLE
Add plant species to NCBITaxonomy voca list.

### ISSUE THREAD

**Issue by KyobinKang** [mwang87/ReDU-MS2-GNPS#201]
I'm making a plant metabolite dataset to be redu-compatible.
Please add up taxon names in the following file to the NCBITaxonomy voca list. We've already searched them and matched them to the NCBI Taxon code number. :)

P.S. I cannot understand why Github does not support .csv for an attachment!

[Plants_species_list_for_ReDU.xlsx](https://github.com/mwang87/ReDU-MS2-GNPS/files/4716101/Plants_species_list_for_ReDU.xlsx)

**Comment by alan-jarmusch** [comment]
Hi @KyobinKang sorry for the delay. The requested NCBITaxa has been added to the sample information template. Thank you for your interest and contribution! Note, the metadata validator will error if you attempt to validate before the next scheduled release.

**Comment by KyobinKang** [comment]
Thanks @alan-jarmusch ! I'll prepare the metadata, wait for the next release, then submit the metadata.
