### ISSUE TITLE
Inclusion of mitragyna  species in the ReDu template

### ISSUE THREAD

**Issue by saghadejia** [mwang87/ReDU-MS2-GNPS#215]
I write to request inclusion of mitragyna species in the ReDu template for metadata, because i have checked but i actually not find any mitragyna specie in the template

**Comment by alan-jarmusch** [comment]
Hi, sorry for the slow reply I've been on a long holiday. are there any species of particular interest in NCBI (https://www.ncbi.nlm.nih.gov/taxonomy)? we are adding things are requested

**Comment by saghadejia** [comment]
We are working on Mitragyna species, these are species needed to be added on the ReDU:  Mitragyna tubulosa, Mitragyna parvifolia, Mitragyna hirsute, Mutragyna diversifolia, Mitragyna rotundifolia, Mitragyna speciosa, Mitragyna ciliate, Mitragyna inermis, Mitrgyna stipulosa and Mitragyna africanus

**Comment by alan-jarmusch** [comment]
thanks. I have added the following based on your request and what is available in NCBI (if it doesn't appear in NCBI it is labeled as "not specified")

**Comment by alan-jarmusch** [comment]
1442754\|Mitragyna   tubulosa
--
1288021\|Mitragyna parvifolia
371154\|Mitragyna hirsuta
170022\|Mitragyna diversifolia
170024\|Mitragyna rotundifolia
170351\|Mitragyna speciosa
not specified\|Mitragyna ciliate
170023\|Mitragyna inermis
not specified\|Mitrgyna stipulosa
not specified\|Mitragyna africanus
