### ISSUE TITLE
Inclusion of taxonomy data

### ISSUE THREAD

**Issue by zaarasmith** [mwang87/ReDU-MS2-GNPS#216]
311410|Labrenzia alba
1402|Bacillus licheniformis
293386|Bacillus stratosphericus
1173585|Ruegeria arenilitoris
1283|Staphylococcus haemolyticus

**Comment by alan-jarmusch** [comment]
Hi, sorry for the slow reply. I was on an extended holiday. I have added these options to the sample information template.

**Comment by alan-jarmusch** [comment]
to access these options, please make a new copy of the sample information template. you can copy and paste whatever information you have already entered. we are currently working to improve this user experience, we apologize for the extra step.
