### ISSUE TITLE
NCBI of Lobophytum soft coral

### ISSUE THREAD

**Issue by viqqikurnianda** [mwang87/ReDU-MS2-GNPS#217]
I would like to request NCBI taxonomy of Lobophytum soft coral as follows:
a). Lobophytum rigidum (NCBI ID: 2484527) 
b). Lobophytum crassum (NCBI ID: 328265)

Thank you

**Comment by alan-jarmusch** [comment]
thank you. I have added both

2484527\|Lobophytum   rigidum
--
328265\|Lobophytum crassum
