### ISSUE TITLE
Addition of multiple species to ReDU

### ISSUE THREAD

**Issue by oolonek** [mwang87/ReDU-MS2-GNPS#219]
Hi all,

We would like to add the following species to Redu.
(0 means  we couldnt find the species in NCBI btw)

Many thanks !

386244|Trichosanthes ovigera
190240|Byttneria aspera
459060|Ficus exasperata
1487832|Pycnocoma chevalieri
761062|Tabernaemontana crassa
429496|Ichnocarpus frutescens
54804|Persicaria chinensis
138163|Globba schomburgkii
676073|Trichosanthes rosthornii
1532000|Acalypha siamensis
159053|Limonia acidissima
62097|Plumeria rubra
258178|Berberis julianae
0|Omphalea bracteata
174187|Amorphophallus paeoniifolius
204149|Ocimum tenuiflorum
4456|Alocasia macrorrhizos
1633398|Croton thorelii
2516471|Cnestis palala
1962698|Baliospermum solanifolium
306515|Aglaia simplicifolia
1962698|Baliospermum solanifolium
141545|Cerbera manghas
0|Astrotrichilia valiandra
84861|Carissa bispinosa
141545|Cerbera manghas
2028265|Croton mavoravina
2028267|Croton meridionalis
316917|Givotia madagascariensis
761058|Tabernaemontana coffeoides
761058|Tabernaemontana coffeoides
0|Jatropha mahafalensis
0|Malleastrum horokoke
187506|Marsdenia verrucosa
0|Plumbago aphylla
0|Nuxia coriacea
312836|Secamone ligustrifolia
4111|Solanum melongena
106616|Bruguiera cylindrica
100569|Ficus racemosa
231906|Garcinia hanburyi
0|Euonymus indicus
0|Tabernaemontana bovina
109864|Mallotus paniculatus
34316|Eucalyptus camaldulensis
0|Antidesma acidum
459167|Quassia africana
141565|Geissospermum laeve
241862|Bagassa guianensis
571348|Balakata baccata

**Comment by Adafede** [comment]
Hi, following @oolonek , here are a few more! :D

[ncbi_organisms.tsv.gz](https://github.com/mwang87/ReDU-MS2-GNPS/files/5530143/ncbi_organisms.tsv.gz)
