### ISSUE TITLE
Add Agilent 6545 to Instrument List in ReDU Template

### ISSUE THREAD

**Issue by ebilbrey** [mwang87/ReDU-MS2-GNPS#221]
Planning to contribute MSMS data collected on an Agilent 6545 QTOF, which has not been added to the instrument list on the Google Sheets ReDU template.
Accepted nomenclature found at https://www.ebi.ac.uk/ols/search?q=6545+&ontology=ms should be:
6545 Q-TOF LC/MS|MS:1002791

**Comment by alan-jarmusch** [comment]
@ebilbrey sorry for the delay. the requested instrument has been added. thank you for your interest!

**Comment by ebilbrey** [comment]
No worries! Thanks for adding. It would also be a good addition to add to the instrument list selection in MassIVE.
