### ISSUE TITLE
Add Species to NCBI Taxonomy

### ISSUE THREAD

**Issue by ebilbrey** [mwang87/ReDU-MS2-GNPS#223]
Planning to contribute data collected, including extract from a species that has not been added to the instrument list on the Google Sheets ReDU template.
Accepted nomenclature should be: 106560|Malus niedzwetzkyana
Found at https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=106560&lvl=3&lin=f&keep=1&srchmode=1&unlock

**Comment by alan-jarmusch** [comment]
I've added it to the template. if you save a new copy the option will be there. I'll put this modification in for the next update - if you complete and validate before that update you will get a validation error. if the only error is for (106560|Malus niedzwetzkyana) then you can proceed to upload it to massive - and it will get updated in the next ReDU rebuild. thanks!
