### ISSUE TITLE
Additional metadata options

### ISSUE THREAD

**Issue by RachelGregor** [mwang87/ReDU-MS2-GNPS#225]
Hi, I wanted to ask you to add a few metadata options:

SampleExtractionMethod methyltertbutylether-methanol-water (2:1:1)

SampleCollectionMethod feces

InternalStandardsUsed ribitol

InternalStandardsUsed ampicillin

MassSpectrometer Agilent GC 7820A-MS 5977B

Thank you!

Rachel Gregor

**Comment by alan-jarmusch** [comment]
Hi Rachel, thanks for your interest. I've added the options. You will find them if you make a new copy of the template - copy and paste anything you had already completed.
