### ISSUE TITLE
Add Species to NCBITaxonomy and Term to SampleTypeSub1

### ISSUE THREAD

**Issue by kerrymcphail** [mwang87/ReDU-MS2-GNPS#226]
Please could you add:
 'salamander' under 'SampleTypeSub1';
under NCBITaxonomy:
Plethodon chattahoochee
Plethodon metcalfi
Plethodon shermani
Plethodon teyahalee
Pseudotriton ruber
Eurycea bislineta
Acris crepitans

Thanks 👍

**Comment by alan-jarmusch** [comment]
thank you - the following were added to taxonomy

263670|Plethodon chattahoochee
315414|Plethodon metcalfi
263671|Plethodon shermani
154591|Plethodon teyahalee
134762|Pseudotriton ruber
134758|Eurycea bislineata
317300|Acris crepitans
