### ISSUE TITLE
Add species to ReDU Sample Information Template v3.0

### ISSUE THREAD

**Issue by JoaoMagc** [mwang87/ReDU-MS2-GNPS#231]
I'm working with some Solanum samples and need to build a metadata table with your model to use later with GNPS. Can you please add the following species to the NCBI taxonomy column?
Solanum argenteum
Solanum asperum
Solanum campaniforme
Solanum cinnamomeum
Solanum cladotrichum
Solanum didymium
Solanum sanctae-catharinae
Solanum schwackeanum
Solanum swartzianum
Solanum vaillanti
Solanum variabile

**Comment by alan-jarmusch** [comment]
hi @JoaoMagc. could you please provide the NCBI taxonomy identifier (if applicable)? https://www.ncbi.nlm.nih.gov/taxonomy

**Comment by JoaoMagc** [comment]
Hey, Alan. Thanks for your response. Here they go:

2072293 | Solanum argenteum
681489 | Solanum asperum
Solanum campaniforme - not found
Solanum cinnamomeum - not found
2598623 | Solanum cladotrichum
2364065 | Solanum didymum
Solanum sanctae-catharinae - not found
2072295 | Solanum swartzianum
282179 | Solanum vaillantii
Solanum variabile - not found

**Comment by JoaoMagc** [comment]
Hey @alan-jarmusch. Just realized I forgot to ask for 
not specified|Solanum schwackeanum 
as well. Could you please also add this one?

**Comment by alan-jarmusch** [comment]
@JoaoMagc it's been added

**Comment by JoaoMagc** [comment]
Thanks, @alan-jarmusch! I have all I need to start working now :)
