### ISSUE TITLE
Please add controlled vocabulary 

### ISSUE THREAD

**Issue by dlforrister** [mwang87/ReDU-MS2-GNPS#232]
Hi, I'm working to upload several plant metabolomics data sets. Can you add the following to the vocabulary? 

1) For 'SampleCollectionMethod' please add: "solid material, dried in silica at room temperature"

2) For 'SampleExtractionMethod' please add "water-acetonitrile 60:40"

3) For 'InternalStandardsUsed' please add "biochanin A". Also, have you considered using CAS numbers or some type of identifier that would be analogous to the NCBI taxonomy control? Just a thought to make it more consistent. 

4)  Can you please add the following species to the `NCBITaxonomy`:

486047|Inga acuminata
486055|Inga cocleensis
487684|Inga laurina
486059|Inga goldmanii        
468147|Inga marginata
486087|Inga thibaudiana
486073|Inga oerstediana
247899|Inga punctata
486071|Inga nobilis
486076|Inga ruiziana
486078|Inga sapindoides
486084|Inga spectabilis
486089|Inga umbellifera
486092|Inga vera
199163|Inga edulis
1620951|Inga cylindrica
1964175|Inga pitmanii
668910|Inga heterophylla
486052|Inga bourgonii
668906|Inga alata
485823|Inga acreana
486082|Inga setosa
668913|Inga venusta
668907|Inga alba
486086|Inga tenuistipula
1954600|Inga lateriflora
670675|Inga fosteriana
670694|Inga suaveolens       
[29] 668912|Inga tomentosa
668909|Inga chartacea
670674|Inga coruscans
670676|Inga ingoides         
486065|Inga leiocalycina
486050|Inga auristellae
668911|Inga poeppigiana
1620953|Inga grandiflora
1186120|Inga rubiginosa
670671|Inga cayennensis
2793465|Inga glomeriflora
597309|Inga paraensis        
688049|Inga gracilifolia
2793475|Inga obidensis
486075|Inga pezizifera
2793483|Inga ulei
1937598|Inga lomatophylla
2793460|Inga brevialata
1937427|Inga splendens
670673|Inga cordatoalata
 1186121|Inga stipularis
486085|Inga striata 
670672|Inga cinnamomea
1964171|Inga fastuosa
1620952|Inga flagelliformis
597307|Inga huberi
1937597|Inga jenmanii
1736652|Inga longiflora      
1186117|Inga longipedunculata 
597305|Inga acrocephala
1186118|Inga loubryana
1186119|Inga melinonis       
597308|Inga nouragensis
1620954|Inga retinocarpa
1964177|Inga virgultosa
597306|Inga brachystachys
668908|Inga brevipes
486094|Inga vismiifolia
486091|Inga velutina
486081|Inga sertulifera
2793474|Inga multinervis
2793468|Inga kursarii
2793457|Inga aria
 2793995|Inga subcapitata
2793473|Inga microcoma
486090|Inga umbratica

5) In addition to the above species we have another 25 species that did not appear in the NCBI Taxonomy and that is because they are new species that have yet to be described and added to NCBI. They are in essence a morphospecies, but we are very confident they are actually species because they are corroborated by traits, morphology, genetics/phylogenies. What would you recommend we do here? Should we do the NCBI for the genus alone and then add a note to the  'SubjectIdentifierAsRecorded' column? 

Thank you,

Dale Forrister

**Comment by alan-jarmusch** [comment]
Hi @dlforrister! thank you for the detailed information. To answer #5 - the options you outline are both okay. You can either add as the genus level (my slight preference) or you can add as the species (in this case the NCBI taxa # would be "not applicable"). Let me know which you prefer and then I'll make all of the updates you requested.

**Comment by dlforrister** [comment]
Ok, I think we can go with just the genus level but we would like to add a note as to what species they actually are in another column. Is that possible within the SubjectIdentifierAsRecorded or is there another column it makes sense to do this.

The genus would be:

162809 | Inga sp
