### ISSUE TITLE
New NCBI species entries addition in the controlled vocabulary

### ISSUE THREAD

**Issue by oolonek** [mwang87/ReDU-MS2-GNPS#235]
Hi @alan-jarmusch and ReDu team,

Could you please add the following species to the ReDu controlled vocabulary ?

Many thanks !

2044324|Codariocalyx gyroides
798326|Ischaemum indicum
1892693|Gentiana pubigera
1898882|Oxyspora paniculata
451700|Corylopsis multiflora
201513|Clerodendrum yunnanense
1348735|Pedicularis henryi
1049785|Peracarpa carnosa
1092581|Hemarthria compressa
435764|Ottochloa nodosa
344832|Pilea plataniflora
50810|Tripterospermum cordatum
49036|Paraboea rufescens
1701078|Eremogone saxatilis
180758|Vaccinium fragile
91508|Apluda mutica
1718245|Hildaea pallens
496686|Pimpinella candolleana
57009|Sambucus javanica
272673|Aglaomorpha bonii
162718|Copaifera salikounda
50346|Saccharum arundinaceum
2100126|Persicaria tenella
171939|Mangifera pentandra
1006144|Tetrastigma strumarum
1052008|Cyperus diffusus
397404|Strombosia grandifolia
1940509|Aubrevillea kerstingii
1521447|Triplochiton scleroxylon
61310|Platycerium angolense
105906|Succisa pratensis
172216|Craterispermum laurinum
233668|Autranella congolensis
312427|Caloncoba welwitschii
103768|Whitfieldia elongata
81982|Pseudoturritis turrita
75960|Cicerbita muralis
1007327|Desplatsia dewevrei
1321794|Chrysophyllum subnudum
59788|Megathyrsus maximus
244001|Asplenium onopteris
340443|Dipterocarpus tuberculatus
2516486|Enkleia malaccensis
338494|Gigantochloa albociliata
1651117|Gnetum edule
1633950|Vaccinium urceolatum
138141|Globba campsophylla
65979|Leersia hexandra
292001|Hopea helferi
2282342|Gigantochloa parvifolia
76444|Fimbristylis dichotoma
432674|Viburnum brachybotryum
241844|Dolichandrone spathacea
2545981|Gonocaryum lobbianum
131256|Arenga caudata
152390|Dipterocarpus retusus
1489667|Hymenocardia punctata
549705|Hymenopyramis brachiata
450288|Piper wallichii
698833|Elsholtzia fruticosa
861395|Gaultheria cuneata
1346085|Millettia congestiflora
185530|Ilex macrocarpa
221766|Cyathula prostrata
751800|Clinopodium megalanthum
99386|Begonia palmata
1872703|Ilex szechwanensis
173671|Aucuba himalaica
539895|Potentilla lineata
642903|Sanicula astrantiifolia
1441986|Goniothalamus gabriacianus
870738|Senna timorensis
1068520|Lobelia seguinii
62858|Satyrium
1054458|Trichosanthes dunniana
170020|Hymenodictyon flaccidum
138164|Globba winitii
1399737|Pouzolzia sanguinea
62865|Satyrium nepalense
909202|Viola yunnanfuensis
45463|Sambucus racemosa subsp. sieboldiana
653096|Phanera ornata
155136|Stauntonia brunoniana
86093|Lindenbergia philippensis
148569|Lygodium salicifolium
324555|Halopegia blumei
748694|Clematis chrysocoma
43864|Buchanania latifolia
2021390|Helwingia omeiensis
489313|Entada gigas
338571|Amaranthus blitum
319607|Phyllanthus pulcher
1592029|Allospondias lakonensis
1529617|Acacia megaladena
1489448|Aporosa planchoniana
83431|Selenicereus
2100677|Mussaenda rehderiana
748691|Clematis brevicaudata
1531353|Galium asperifolium
198854|Indigofera amblyantha
1237824|Suregada procera
557013|Mischocarpus pentapetalus
928046|Chlorophytum minor
38789|Clematis apiifolia
748704|Clematis meyeniana
69848|Carex baccans
1127383|Crotalaria laevigata
2291900|Cyphostemma elephantopus
857597|Dombeya lucida
1007786|Gladiolus italicus
756371|Cyphostemma laza
3990|Euphorbia
48523|Ehretia cymosa
209324|Euphorbia cedrorum
2047853|Ehretia microcalyx
303142|Halleria tetragona
212953|Euphorbia pervilleana
185054|Cynanchum mahafalense
178803|Cyphostemma
1171751|Dombeya greveana
69116|Adansonia za
655924|Senna meridionalis
318970|Commiphora brevicalyx
80335|Commiphora monstruosa
69114|Adansonia rubrostipa
387526|Adenia monadelpha
204110|Capitanopsis angustifolia
80336|Commiphora simplicifolia
578535|Calopyxis grandidieri
1173008|Commiphora lamii
387527|Adenia olaboensis
2485361|Capitanopsis cloiselii
202626|Cadaba virgata
184278|Cerbera venenifera
318969|Commiphora aprevalii
1132602|Crotalaria fiherenensis
1132605|Crotalaria grevei
511494|Boscia longifolia
117962|Kalanchoe arborescens
439928|Megistostegium microphyllum
58040|Nymphaea nouchali
319571|Phyllanthus casticum
141600|Plectaneia stenophylla
658448|Megistostegium nodulosum
289730|Operculicarya
1548629|Pluchea grevei
80903|Kalanchoe linearifolia
439929|Megistostegium perrieri
1592051|Operculicarya pachypus
439908|Hibiscus ferrugineus
289731|Operculicarya decaryi
1009579|Loeseneriella urceolus
1225832|Psiadia glutinosa
1097630|Solanum erythracanthum
115666|Solanum macrocarpon
201021|Turraea sericea
4184|Uncarina grandidieri
166048|Uncarina
1225819|Psiadia angustifolia
1879238|Solanum heteracanthum
227487|Typhonodorum lindleyanum
43543|Salvadora angustifolia
74960|Tambourissa amplifolia
191659|Sansevieria metallica
171014|Cycas siamensis
1747696|Dillenia obovata
2594747|Eriocaulon sexangulare
1225699|Solori scandens
1381998|Dischidia nummularia
1818588|Dolichandrone columnaris
2306765|Connarus semidecandrus
682665|Euodia simplicifolia
13529|Flagellaria indica
1367315|Diospyros pilosanthera
640652|Dillenia hookeri
1489652|Garcinia lanessanii
1095265|Antidesma ghaesembilla
1489464|Buchanania reticulata
941537|Cananga brandisiana
345108|Cissus repanda
1051490|Xerophyta dasylirioides
709053|Artocarpus nitidus
1229245|Bauhinia bracteata
577036|Cleistanthus tomentosus
1755451|Ampelocissus arachnoidea
416185|Atalantia citroides
515877|Xerosicyos perrieri
1489466|Calamus salicifolius
149356|Causonis trifolia
388302|Xerosicyos pubescens
1489748|Mangifera duperreana
1879252|Solanum sakhanii
429529|Spirolobium cambodianum
218181|Lithocarpus elegans
1248968|Olax imbricata
2498814|Sesbania javanica
1489751|Melastoma saigonense
2100654|Mussaenda cambodiana
1227989|Bauhinia viridescens
1006109|Tetrastigma cruciatum
1489450|Aporosa villosa
2021211|Indocypraea montana
148567|Lygodium palmatum
34175|Tradescantia zebrina
58032|Dioon
2082994|Embelia basaal
1071044|Uraria crinita
69391|Wrightia arborea
1117039|Sphagneticola calendulacea
539024|Indigofera atriceps
292647|Bismarckia nobilis
2184935|Hodgsonia macrocarpa
4640|Musa
190249|Sterculia lanceolata
469944|Garcinia verrucosa
469924|Garcinia chapelieri
1489631|Connarus cochinchinensis
161027|Moringa drouhardii
1842781|Senna gaudichaudii
62340|Hydrocharis dubia
538304|Piper massiei
714502|Solena amplexicaulis
1750992|Streblus ilicifolius
1218914|Stereospermum neuranthum
1353447|Dalbergia dongnaiensis
231911|Garcinia tinctoria
1981914|Phoebe tavoyana
128318|Isertia coccinea
174209|Dracontium polyphyllum

**Comment by alan-jarmusch** [comment]
Hi! Thanks for your interest.

I've updated the template. And the requested have been added. You may receive an error message during validation if you try to validate before the system updates - but if these are the only errors - then you can feel free to submit to massive.ucsd.edu and the data will be automatically "found" by ReDU when it updates.
