### ISSUE TITLE
Need more approved terms

### ISSUE THREAD

**Issue by naiosa** [mwang87/ReDU-MS2-GNPS#240]
It says to contact admins if the approved vocab is not sufficient. I am planning to submit different mutant strains of B. thailandensis and I am unsure which column I can specify the mutations/different strain names for each file. Also, for the DOIDCommonName, I would like to use Melioidosis DOID:5052 as well for my files, but that is not in the approved vocab either. Thank you for your help.

**Comment by mwang87** [comment]
@alan-jarmusch

**Comment by naiosa** [comment]
Hi, Any update on this?

**Comment by alan-jarmusch** [comment]
57975|Burkholderia thailandensis is currently in the validator. there isn't a specific ability to add strains. you would have to perform that analysis separately from the current ReDU infrastructure.

I have added DOID:5052 as indicated.
