### ISSUE TITLE
 Need more approved terms (SampleType)

### ISSUE THREAD

**Issue by Adafede** [mwang87/ReDU-MS2-GNPS#243]
Hi,

I am actually trying to add ReDu compliant metadata of previously uploaded MassIVE datasets.

I have samples that are coming from Fungi, but uncultured ones. 

I think there is no appropriate term for that?

Best,

**Comment by alan-jarmusch** [comment]
I have added "fungi' as a sample type and 'fungi_insitu' in SampleTypeSub1 to represent your uncultured samples. the metadata will be updated

**Comment by Adafede** [comment]
Thank you!
