### ISSUE TITLE
Additional ReDu terms requested

### ISSUE THREAD

**Issue by RobertJansen80** [mwang87/ReDU-MS2-GNPS#245]
To upload some data to MassIVE, I would like to request entries fot the follwoing NCBITaxonomies
- 380242|Candidatus Brocadia fulgida
- 174633|Candidatus Kuenenia stuttgartiensis
- 236756|Candidatus Scalindua

Ans as extraction solvent
- 40:40:20, acetonitrile, methanol, water 

Also, would it be possible to include the Agilent 6546 QTOF to the instrument list?

Thanks!

Robert Jansen

**Comment by RobertJansen80** [comment]
Hi Ming,

Sounds good. Good luck with starting your lab!

Robert
________________________________
Van: Ming Wang ***@***.***>
Verzonden: donderdag 30 juni 2022 00:07
Aan: mwang87/ReDU-MS2-GNPS ***@***.***>
CC: Jansen, R.S. (Robert) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [mwang87/ReDU-MS2-GNPS] Additional ReDu terms requested (Issue #245)


Hi @RobertJansen80<https://urldefense.com/v3/__https://github.com/RobertJansen80__;!!HJOPV4FYYWzcc1jazlU!_TJr2sAZsCjmNFnEeGkQOAoAYXn9WKNO5v5YrlCAFUXZ7AVCeQpcpQ2vthMwfpPRV30pQMk9zs6_IsftNDOrTzvDYw$> Sorry for the delay, its been a busy few months as I'm transition to my new faculty position at UCR. This will include a migration of ReDU and one thing I want to do is a bit of a refactor so that we can make the terms more extensible so even you can propose additions so it becomes way more responsive. Once things are settled later in the summer, lets work together to get this done!

**Comment by alan-jarmusch** [comment]
I've updated the metadata to include your organisms as well as the solvent and mass spec terms below.
'acetonitrile-methanol-water (2:2:1)'
'Agilent 6546 QTOF|not available'
