### ISSUE TITLE
New required Terms for microbeMASST data submission

### ISSUE THREAD

**Issue by Pbourceau** [mwang87/ReDU-MS2-GNPS#249]
Dear ReDU Team,

I would like to submit some data for microbeMASST and I need some new Terms for the Table:

NCBITaxonomy
285279|Pseudovibrio ascidiaceicola 
1137780|Polaribacter porphyrae
943941|Postechiella marina
272164|Olleya marilimosa
223958|Exiguobacterium oxidotolerans
1972512|Loktanella acticola
979|Cellulophaga lytica
291985|Erythrobacter vulgaris
2020714|Olleya algicola
192421|Planococcus maritimus 
1524257|Limimaricola aestuariicola
326329|Polaribacter dokdonensis
1784714|Arcticibacterium luteifluviistationis 
1130723|Maribacter aestuarii
255984|Erythrobacter aquimaris
1853311|Lutibacter oceani
691689|Lutibacter flavus
43656|Pseudoalteromonas denitrificans
326329|Polaribacter dokdonensis
1828|Rhodococcus fascians
159346|Roseibacterium elongatum
326329|Polaribacter dokdonensis
136468|Vibrio lentus 
320912|Maribacter dokdonensis
576131|Lentibacter algarum
283736|Leeuwenhoekiella aequorea
943941|Postechiella marina 
1038014|Aquimarina amphilecti
2182384|Erythrobacter aureus
1136748|Algibacter aquimarinus
364200|Cognatiyoonia koreensis
1940281|Hoeflea sp. 
229204|Flavobacterium frigoris
104|Cyclobacterium marinum
237019|Algoriphagus chordae
221126|Algibacter lectus
208199|Bacillus hwajinpoensis
552386|Vibrio gallaecicus
1884876|Winogradskyella flava
483016|Lutimonas saemankumensis
523845|Methanothermococcus thermolithotrophicus strain DSM 2095
1434108|Methanosarcina barkeri strain DSM 800 or MS
79929|Methanothermobacter marburgensis strain DSM 2133 
1122233|Methermicoccus shengliensis strain DSM 18856
573063|Methanocaldococcus infernus strain ME
243232|Methanocaldococcus jannaschii  strain DSM2661 JAL-1
1341692|Clostridium autoethanogenum strain DSM 10061 
579137|Methanocaldococcus vulcanius strain DSM 12094 M7
224325|Archaeoglobus fulgidus strain DSM 4304 VC-16
2246|Haloferax volcanii
444515|Maribacter forsetii
411153|Gramella forsetii
1420851|Methyloprofundus sedimenti strain WF1

SampleExtractionMethod
acetonitrile-methanol-water (2:2:1)

Thank you very much!

Cheers

Patric Bourceau

**Comment by alan-jarmusch** [comment]
thank you - I've updated the metadata.
