### ISSUE TITLE
New required Terms for microbeMASST data submission

### ISSUE THREAD

**Issue by dingsux3** [mwang87/ReDU-MS2-GNPS#250]
Dear Ming,
Congratulations on your new faculty position at UCR.

I would like to submit some data for microbeMASST and I need some new Terms for the Metatable:

SampleType
archaea

SampleTypeSub1
Lake, isolates

NCBITaxonomy

2841257|Halapricum desulfuricans
253108|Natronolimnobius baerhuensis
253107|Natronolimnobius innermongolicus
2917812|Natronocalculus amylovorans
2917711|Natranaeroarchaeum aerophilus
1679096|Halococcoides cellulosivorans
2055893|Halalkaliarchaeum desulfuricum
1679083|Natrarchaeobius chitinivorans
1679076|Natronobiforma cellulotropha
1679091|Natrarchaeobius haloalkaliphilus
2044521|Natronolimnobius sulfurireducens

SampleExtractionMethod
MeOH:DCM:phosphate buffer (2:1:0.8,v:v:v)
Bligh and Dyer extraction-MeOH:DCM:phosphate buffer (2:1:0.8,v:v:v), MeOH:DCM:trichloroacetic acid (2:1:0.8,v:v:v)

InternalStandardsUsed
deuterated betaine lipid {1,2-dipalmitoyl-sn-glycero-3-O-40-[N,N,N-trimethyl(d9)]-homoserine
1-O-hexadecyl-2-acetyl-snglycero-3-phosphocholine

Many thanks!

Best wishes,
Su Ding

**Comment by dingsux3** [comment]
SampleExtractionMethod
MeOH:DCM:phosphate buffer (2:1:0.8,v:v:v)
Below is the same. Don't know why it comes out a emoji:)

**Comment by dingsux3** [comment]
The emoji under the SampleExtrationMethod is v: v: v

**Comment by alan-jarmusch** [comment]
SampleType
archaea = added

SampleTypeSub1
Lake, isolates = please use "water_surface" for lake, "water_surface_isolate" for isolates

NCBITaxonomy

2841257|Halapricum desulfuricans
253108|Natronolimnobius baerhuensis
253107|Natronolimnobius innermongolicus
2917812|Natronocalculus amylovorans
2917711|Natranaeroarchaeum aerophilus
1679096|Halococcoides cellulosivorans
2055893|Halalkaliarchaeum desulfuricum
1679083|Natrarchaeobius chitinivorans
1679076|Natronobiforma cellulotropha
1679091|Natrarchaeobius haloalkaliphilus
2044521|Natronolimnobius sulfurireducens

SampleExtractionMethod
MeOH:DCM:phosphate buffer (2:1:0.8,v✌️v)
Bligh and Dyer extraction-MeOH:DCM:phosphate buffer (2:1:0.8,v✌️v), MeOH:DCM:trichloroacetic acid (2:1:0.8,v✌️v)

InternalStandardsUsed
deuterated betaine lipid {1,2-dipalmitoyl-sn-glycero-3-O-40-[N,N,N-trimethyl(d9)]-homoserine
1-O-hexadecyl-2-acetyl-snglycero-3-phosphocholine
