### ISSUE TITLE
New required terms for MicrobeMAAST data submission

### ISSUE THREAD

**Issue by raimofranke** [mwang87/ReDU-MS2-GNPS#251]
Hi Ming,

for data submission I would need the following additional terms:

internal standards:
trimethoprim, nortriptylin, glipizide, caffeine and naproxen

Mass spectrometer:
Bruker timsTOF Pro

I am also not sure how to indicate clinical isolates of bacteria - how should I do this and where can put the name of the clinical isolate - we have several clinical isolates of Pseudomonas aeruginosa.

Thanks a lot and best wishes,
Raimo

**Comment by alan-jarmusch** [comment]
Hi,
i've updated the metadata. 'timsTOF Pro|MS:1003005'
and other terms.

for the isolates - we don't record anything other than the NCBI number. Your analysis would have to be done outside of the ReDU infrastructure at present.

**Comment by raimofranke** [comment]
Hi Alan, I cannot find the new terms in the ReDU Sample Information Template - it is still version 3.0 - where can I download an updated template? Thanks and best wishes, Raimo
