### ISSUE TITLE
New required Terms for microbeMASST data submission

### ISSUE THREAD

**Issue by KyobinKang** [mwang87/ReDU-MS2-GNPS#252]
I can imagine that microbeMASST will raise a number of similar issues here XD

Anyway, please put the below into the NCBI taxonomy vocabulary list.

83250|Tyromyces choineus
5632|Lenzites betulinus
1611329|Cerrena aurantiopora
40452|Trichaptum abietinum
5325|Trametes versicolor
not specified|Trametes trogii
76333|Cerrena consors
38799|Neolentinus lepideus
655091|Coriolopsis strumosa
227965|Perenniporia fraxinea
not specified|Pycnoporus coccineus
158312|Microporus vernicipes
not specified|Perenniporia minutissima
83254|Skeletocutis nivea
103381|Lopharia cinerascens
40435|Datronia mollis
1840328|Trametopsis cervina
90312|Cerrena unicolor
1840328|Daedaleopsis styracina
5639|Polyporus arcularius
76128|Nigroporus vinosus
139102|Cinereomyces lindbladii
1260784|Neofavolus alveolaris
252820|Microporus affinis
82310|Phlebiopsis gigantea
not specified|Lenzites styracina
1586344|Perenniporia koreana
1931348|Phlebiopsis castanea

Thanks!
Kyo Bin

**Comment by alan-jarmusch** [comment]
thank you for your contribution the validator will be updated.
