### ISSUE TITLE
New terms to be added in the NCBITAxon controlled vocabulary.

### ISSUE THREAD

**Issue by oolonek** [mwang87/ReDU-MS2-GNPS#259]
Hi, 

Could the following terms be added to the taxon list ?

105696|Epicoccum nigrum
11092585|Gibberella avenacea
112178|Arthrinium phaeospermum
114231|Khuskia oryzae
119927|Alternaria tenuissima
119957|Ulocladium chartarum
1343368|Penicillium aurantiogriseum
1343369|Penicillium brevicompactum
1343383|Penicillium commune
161657|Davidiella macrospora
162415|Pestalotiopsis funerea
1896172|Mortierella alpina
2074758|Alternaria alternata
27334|Penicillium expansum
29917|Cladosporium cladosporioides
29918|Cladosporium herbarum
37840|Pestalotiopsis
40559|Botrytis cinerea
5498|Cladosporium
5503|Curvularia lunata
61284|Gibberella tricincta
63577|Trichoderma atroviride
64524|Mortierella hyalina
690891|Leptosphaerulina australis
69773|Penicillium glabrum

Note that some might already be present in the ReDU sheet.
Many thanks !

**Comment by alan-jarmusch** [comment]
thank you for your contribution - I've updated the validator. I apologize for the delay.
