### ISSUE TITLE
Addition to ReDUMS2_controlled_vocabulary (MicrobeMASST)

### ISSUE THREAD

**Issue by RachelGregor** [mwang87/ReDU-MS2-GNPS#261]
Hello hello! I have a few new terms to add. Most of the strains here are not in NCBI, for the ones that are I included the number. Thank you!! :)

Shewanella sp.
Colwellia sp.
Motilimonas sp.
Arenibacter sp.
Acinetobacter sp.
Phaeobacter sp.
1486281|Roseovarius sp.
Paracoccus sp. 
1967289|Oceanicola sp.
2058088|Vibrio sp. vnigr-6D03

**Comment by alan-jarmusch** [comment]
these have been added to the validator - thanks. Sorry for the delay.
