### ISSUE TITLE
Addition to ReDUMS2_controlled_vocabulary (MicrobeMASST)

### ISSUE THREAD

**Issue by andisichert** [mwang87/ReDU-MS2-GNPS#262]
Dear Ming Wang,

can you please add the following terms to the taxon list?

1236|Gammaproteobacteria
12916|Acidovorax
47420|Hydrogenophaga
57739|Vogesella
65657|Hydrogenophaga flava
70775|Pseudomonas plecoglossicida
76980|Ahrensia kielensis
83618|Pseudoxanthomonas
196795|unclassified Sulfitobacter
196821|unclassified Pseudomonas
196834|unclassified Colwellia
221126|Algibacter lectus
248906|Zobellia laminariae
454148|Roseibacillus persicicus
1128912|Paraglaciecola mesophila KMM 241
1224307|Rhizobium arsenicireducens
1250001|Olleya sp. Hel_I_94
1397108|Celeribacter marinus
1608400|Algibacter amylolyticus
1806669|Neptuniibacter pectenicola
2614692|unclassified Nitrincola
2614931|unclassified Hoeflea
2615011|unclassified Psychroserpens
2623462|unclassified Pacificibacter
2627644|unclassified Henriciella
2629323|unclassified Roseibium
2637149|unclassified Luteolibacter
2643887|unclassified Mariniflexile
2676099|Lentimonas sp. CC4

Thank you so much!
Andi

**Comment by alan-jarmusch** [comment]
these have been added to the validator - thanks. Sorry for the delay.
