### ISSUE TITLE
Generating Pie Distributions in GNPS FBMN

### ISSUE THREAD

**Issue by jakeulrich** [mwang87/ReDU-MS2-GNPS#267]
I've been trying to differentiate between my samples in a metadata .txt file in order t generate pie distributions in my molecular networks (FBMN, I can do it easily in classical networkin) but I believe I may be doing something wrong. I have a few questions:

1.) I am based on a federal laptop, which cannot access google sheets. I've downloaded the template from my personal device and have been making my metadata tables with this. Is this an acceptable approach?

2.) Do my files need to be associated to a Massive dataset and thus have massive ID for this feature to work?

3.) Am I missing something where the pie charts are generated in a different component on GNPS for FBMN and that's my issue?

**Comment by mwang87** [comment]
1. Totally fine
2. Yes, the raw data must be public
3. You don't need to have any sort of FBMN analysis to contribute to ReDU

**Comment by jakeulrich** [comment]
Just to clarify, in order for the pie charts in the molecular network to be generated during FBMN, the data files must be public and in ReDU?

**Comment by mwang87** [comment]
No, you can analyze your private data. ReDU is so you can share with others your data and metadata describing it so its findable and re-usable.

**Comment by jakeulrich** [comment]
Okay, great thank you!
