### ISSUE TITLE
Additonal options for existing columns and new columns for environmental sampling

### ISSUE THREAD

**Issue by kerrymcphail** [mwang87/ReDU-MS2-GNPS#51]
Please add options to column
Analysis_SampleCollectionMethod:
"marine water"
"fresh water"
"marine water, solid phase extraction (PPL)"
"fresh water, solid phase extraction (PPL)"
"liquid, solid phase extraction (PPL)"

ATTRIBUTE_Curated_SampleType_Sub1:
"reference material_marinewater"
"reference material_freshwater" 

Possible columns for environmental data:
GPS coordinates - latitude and longitude
Depth in meters (terrestrial = 0; up in trees = +X m; in water = -Z m)
Time of day (in 24 h clock?)  <this may be important for diurnal rhythms of e.g. algae, marine invertebrates>
Sampling site <(e.g. Algoa Bay, Schoenmakerskop, or Whitesands Reef)>

**Comment by alan-jarmusch** [comment]
**Thank you for the suggested additions and your interest in ReDU!** <br> In an attempt to restrict uncontrolled inflation of terms, we have added options or have suggested the use of existing terms that we believe capture your information sufficiently. We realize this restriction may result in the loss of specificity. Therefore, the standard ReDU sample information should be used for broad assessments and data exploration, and suggest that more detailed analysis should be performed using additional metadata from each study (accessed via individual MassIVE ID). If additional terms are necessary or if you believe the added options are insufficient, we welcome discussion via a reply to this message.<br> Thank you again for your interest in ReDU, -the ReDU admins <br>

**Re: Analysis_SampleCollectionMethod:**
* the term "liquid" should be used to describe the "marine water" and "fresh water" as the "...SampleType" and "...SampleType_Sub1" capture this information.
* the term "liquid, solid phase extraction (PPL)" has been added and should be used to capture the terms "marine water, solid phase extraction (PPL)", "fresh water, solid phase extraction (PPL)", "liquid, solid phase extraction (PPL)" in the "...SampleCollectionMethods"


**RE: ATTRIBUTE_Curated_SampleType_Sub1:**
*  the following options have been added to "...SampleType_Sub1":  "environmental_freshwater_water" and "environmental_saline_water".
* please use "environmental" in "...SampleType" with these options.

**Re: Suggested columns for environmental data**
* the suggestions are greatly appreciated and have been noted.

**Comment by kerrymcphail** [comment]
Another option request!
ATTRIBUTE_Curated_SampleType_Sub1:
Consider adding 
"environmental_tunicate"
"environmental_sponge"  or in this case "environmental_marine_invertebrate" ...or
"marine organism" 
"terrestrial organism"

Note that a tunicate is NOT an invertebrate, thus sponges and tunicates should not be lumped together as invertebrates

Or maybe this should not be a controlled variable option because different people may want to compare different groups of organisms (specific corals - soft or hard are very different to eachother).  It is conceivable that this is equally applicable to terrestrial organisms...flow of conscious thought here...

Issue is that both Ane and Kerry want to add (marine) tunicate samples and there is no option that is applicable.

Kerry and Ane

**Comment by alan-jarmusch** [comment]
**Thank you for the suggested additions and your interest in ReDU!** 
In an attempt to restrict uncontrolled inflation of terms, we have added options or have suggested the use of existing terms that we believe capture your information sufficiently.

Please enter the terms in **SampleType** and the organism using the **NCBITaxonomy**

If additional terms are necessary or if you believe the added options are insufficient, we welcome discussion via a reply to this message.
Thank you again for your interest in ReDU, -the ReDU admins
