### ISSUE TITLE
requesting additional options for SampleTypeSub1, for built environment samples

### ISSUE THREAD

**Issue by mccall-lab-OU** [mwang87/ReDU-MS2-GNPS#63]
I have a data set of office, teaching and research buildings. The only built environment-related option in SampleTypeSub1 is "house", which I don't think covers public building types such as these (much different traffic patterns, many more divers visitors etc). I think at minimum something like "commercial building" or "public building" might be useful. Thanks!

**Comment by alan-jarmusch** [comment]
Thank you for the suggested additions and your interest in ReDU! 
In an attempt to restrict uncontrolled inflation of terms, we will add terms as they become necessary. We realize this restriction may result in the loss of specificity.  If you have specific needs, we would be happy to discuss the additions via a reply to this message.
Thank you again for your interest in ReDU, -the ReDU admins

**Comment by mccall-lab-OU** [comment]
There's a typo in the options: "commerical_building" should be "commercial_building"
