### ISSUE TITLE
requesting additional metadata options 

### ISSUE THREAD

**Issue by mccall-lab-OU** [mwang87/ReDU-MS2-GNPS#64]
A few requests / issues with version 3.0:
1. I have samples with cultured mammalian cells, as well as parasite cultures (protozoan eukaryote, _Trypanosoma cruzi_), neither of which can fit any of the current culture types (culture_bacterial or culture_fungal), in both SampleType and SampleTypeSub1. 
I also noticed that there are redundant options in SampleTypeSub1, with both bacterial culture and culture_bacterial.

2. Have you considered adding some kind of dictionary? Right now, I am uncertain if "tissue" in SampleTypeSub1 also covers fecal material, or if I should use "biofluid". I can figure it out from looking at other people's data, but this should be made more clear to naive users.

3. Add "dichloromethane-methanol (3:1) to SampleExtractionMethod. This is a very common extraction protocol for us (per Want et al, Nature protocols 2013).

4. did you want to differentiate between QExactive Plus, QExactive HF, etc and QExactive for the MassSpecrometer, or does QExactive cover all other models? You do have detailed separation available for Maxis, so I think this is also warrented for QE series. 

5. Although the column description instructions for SampleType say "enter an option from the controlled vocabulary - please use lowest level that applies (for example, human should be chosen over mammalia_NOS)", human and mammalia_NOS are not available as options in my view of the file, only "animal". From other files submitted, I can see that people have been using "animal" for human samples, but then this directly contradicts the instructions.

6. Suggest changing ChromatographyAndPhase "mixed mode (Scherzo SM-C18)" to just mixed mode. Otherwise, you'll end up having to add a whole bunch of options to cover different manufacturer's options. For example, I use polar C18 columns from Phenomenex, which have the same idea as the Scherzo, but different stationary phase material.

Thanks!

**Comment by mccall-lab-OU** [comment]
Also, "NOS" should be defined. I'm assuming it means "not specified", but I can't find that info anywhere.

**Comment by alan-jarmusch** [comment]
Thank you for the suggested additions and your interest in ReDU! With a recent update, some of the instructions are currently out of date. The comments are greatly appreciated. We are working to correct those issues.
Specific Re: below

1) additional categories have been added to the sample information template.
**SampleType**
> culture_mammalian
> culture_multiplespecies
**SampleTypeSub1**
> culture_mammalian
> culture_multiplespecies
There are only a few culture data sets currently, we would like to use the Sub1 category to specify culture media (if that information is available). 

2) the majority of cases should be clear (e.g. blood); however, the suggested dictionary is a good idea which will be implemented in version 2.0. feces would be considered a biofluid

3) dichloromethane-methanol (3:1) has been added as an option.

4) yes, the specifics of the instrument should be listed. we will be adding information to this list, in the meantime, you can suggest a term.

5) will be resolved with an update in documentation after the most recent update.

6) noted, this term is very infrequently used currently - we can considering updating the data sets which use this in the next update.

Thank you again for your interest in ReDU, -the ReDU admins

**Comment by mccall-lab-OU** [comment]
Thanks. In the NCBITaxonomy column, _Trypanosoma cruzi_ is missing (NCBI taxon 5693). One thought: would it be possible to link somehow back to NCBI, so that as long as we know the taxon number and format it properly, we can add it ourselves? Otherwise you'll be getting a lot of requests to add more taxon ids...

**Comment by alan-jarmusch** [comment]
5693|Trypanosoma cruzi has been added.
in future versions, we will link out to NCBI as well as pull down all taxonomic information - development for v2.0
