### ISSUE TITLE
Download button for all identifications in all files

### ISSUE THREAD

**Issue by alan-jarmusch** [mwang87/ReDU-MS2-GNPS#83]
add option in title bar of homepage to download the ReDU database (annotations) and clarify the download database button that currently exists is the sample information database

**Comment by mwang87** [comment]
This is so large that I'd hesitate to offer this. Would require a feature to dump the file, then end point to retrieve it.

**Comment by cmaceves** [comment]
What do you mean by "end point to retrieve it"? As in the addition of a button linked to the back end function that dumps the file? Also I assume I would be writing a tester to go with this? @mwang87

**Comment by mwang87** [comment]
There is a web api url to serve up the file. 

Yes there would be a test to make sure the output is working.

**Comment by alan-jarmusch** [comment]
download button that points to massive ftp link ftp://massive.ucsd.edu/MSV000084206/other/ReDU_all_identifications.tsv

clarity: distinguished from sample information database download button.
