### ISSUE TITLE
BUG - file # does not update when applying filters and performing sample information associations

### ISSUE THREAD

**Issue by alan-jarmusch** [mwang87/ReDU-MS2-GNPS#87]

**Comment by cmaceves** [comment]
@alan-jarmusch are you referring to the "Number of Files" column under the "Explore Chemical Annotations and Associated Sample Information in all Public Data" link?

**Comment by alan-jarmusch** [comment]
https://redu.ucsd.edu/compoundslist#%7B%22filenames%22%3A%5B%22f.MSV000080450%2Fccms_peak%2FAqueous%20extraction%20mzxml%2FP2-H3_RH3_01_858.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FOrganic%20extraction%20mzxml%2FP6-F4_RF4_01_1179.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FAqueous%20extraction%20mzxml%2FP8-F4_RF4_01_1491.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FOrganic%20extraction%20mzxml%2FP4-G12_RG12_01_929.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FOrganic%20extraction%20mzxml%2FP4-H3_RH3_01_932.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FAqueous%20extraction%20mzxml%2FP8-F3_RF3_01_1490.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FOrganic%20extraction%20mzxml%2FP6-F5_RF5_01_1180.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FAqueous%20extraction%20mzxml%2FP8-F5_RF5_01_1492.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FAqueous%20extraction%20mzxml%2FP2-G12_RG12_01_849.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FOrganic%20extraction%20mzxml%2FP6-F3_RF3_01_1178.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FOrganic%20extraction%20mzxml%2FP4-H1_RH1_01_930.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FAqueous%20extraction%20mzxml%2FP2-H1_RH1_01_850.mzXML%22%2C%22f.MSV000080450%2Fccms_peak%2FAqueous%20extraction%20mzxml%2FP2-H3_RH3_01_856.mzXML%22%5D%7D
