### ISSUE TITLE
Adding optional column with qiita sample identifier

### ISSUE THREAD

**Issue by mwang87** [mwang87/ReDU-MS2-GNPS#89]

**Comment by alan-jarmusch** [comment]
add a column to template for Qiita sample identifier. used for associating MS filenames with Qiita and pulling in additional information via redbiom

**Comment by mwang87** [comment]
name it qiita_id

**Comment by alan-jarmusch** [comment]
@mwang87  - column "sample_name" added to metadata sheet.
readme information below

sample_name | character string | Encouraged (if data present in Qiita) | No | enter the sample_name of a corresponding sequencing file in Qiita (https://qiita.ucsd.edu/) for cross-platform connectivity. identifier must be exact and prepended with the Qiita identifier | 10317.000001032
-- | -- | -- | -- | -- | --

**Comment by mwang87** [comment]
I feel like sample_name is too generic of a name. It should qiita_sample_name or something like that.

**Comment by alan-jarmusch** [comment]
@mwang87 if we call it qiita_sample_name (I agree) in the metadata - can we change on our end to sample_name to be compatible with Qiita?

**Comment by mwang87** [comment]
Yes, I think this is a good option.

**Comment by alan-jarmusch** [comment]
okay done. updated.

qiita_sample_name | character string | Encouraged (if data present in Qiita) | No | enter the sample_name of a corresponding sequencing file in Qiita (https://qiita.ucsd.edu/) for cross-platform connectivity. The identifier must be exact and prepended with the Qiita identifier. *Note, files names should be entered as present in Qiita which does not allow for underscores or special characters | 10317.000001032
-- | -- | -- | -- | -- | --

**Comment by alan-jarmusch** [comment]
@mwang87 need to add code to rename when pulling in qiita information. I'll let you handle when coding that part.
